[pytest]
pythonpath = .
python_files = test_*.py
python_classes = Test*
python_functions = test_*
testpaths = app/tests
filterwarnings =
    ignore::DeprecationWarning
    ignore::pydantic.PydanticDeprecatedSince20